site: Harsh Browns
url: https://visitmy.website
title: Harsh Browns
description: Steve Messer’s website. 
twitter:
  username: stevenjmesser
  card: summary
  creator: stevenjmesser
author:
  twitter: stevenjmesser
  name: Steve Messer
  avatar:
  email: #youremail
  url: https://visitmy.website
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"